# dart-daap-client
# pubspec.yaml


name: "daapc"
version: "0.3.2"
description: >-
  dart-daap-client is a Dart DAAP (Digital Audio Access Protocol) protocol client library
homepage: "https://github.com/vint21h/dart-daap-client/"
repository: "https://github.com/vint21h/dart-daap-client/"
issue_tracker: "https://github.com/vint21h/dart-daap-client/issues/"
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  http_auth: "^1.0.0"
  http: "^0.13.1"
  interpolator: "^0.1.0"
  mime: "^1.0.0"
dev_dependencies:
  effective_dart: "1.3.2"
  nock: "1.2.0"
  test: "1.20.1"
  coverage: "1.1.0"
