# dart-daap-client
# pubspec.yaml


name: "daapc"
version: "0.0.0"
description: >-
  A DAAP (Digital Audio Access Protocol) client library
homepage: "https://github.com/vint21h/dart-daap-client/"
repository: "https://github.com/vint21h/dart-daap-client/"
issue_tracker: "https://github.com/vint21h/dart-daap-client/issues/"
environment:
  sdk: ">=2.12.2 <3.0.0"
dependencies:
  http: "0.13.1"
  http_auth: "1.0.0"
  interpolator: "0.1.0"
dev_dependencies:
  test: "1.16.8"
  nock: "1.2.0"
  effective_dart: "1.3.1"
