# daap-client
# pubspec.yaml


name: daapc
version: 0.0.0
description: >-
  DAAP (Digital Audio Access Protocol) client library
homepage: https://github.com/vint21h/daap-client/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: "0.12.2"
  fluri: "1.3.0"
  http_auth: "0.3.1"
  test: "1.15.4"
  nock: "1.1.2"
  test_coverage: "0.5.0"
