# dart-daap-client
# .github/workflows/build.yml


name: "build"
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
  workflow_call:
jobs:
  check-requirements:
    uses: "./.github/workflows/check-requirements.yml"
  check:
    uses: "./.github/workflows/check.yml"
  test:
    uses: "./.github/workflows/test.yml"
    needs: ["check"]
  coveralls:
    uses: "./.github/workflows/coveralls.yml"
    needs: ["test", "check"]
